name: Build

on:
  push:
    branches:
      - master

jobs:
  Android:
    name: Android
    runs-on: ubuntu-latest
    steps:
      - name: Check out git repository
        uses: actions/checkout@v4

      - name: Setup Env
        uses: ./.github/actions/setup

      - name: Install npm dependencies
        run: npm ci

      - name: Build Packages
        env:
          DISABLE_SVG: 1
        shell: bash
        run: |
          cd android
          # Build Debug APK (no signing required)
          ./gradlew assembleDebug

      # Push tag to GitHub if package.json version's tag is not tagged
      - name: Get package version
        run: |
          Package_Version=$(node -p "require('./package.json').version")
          echo "PACKAGE_VERSION=$Package_Version" >> $GITHUB_ENV

      - name: Generate file MD5
        rtn: |
          cd android/app/build/outputs/apk/debug
          md5sum *.apk

      - name: Upload Artifact
        uses: ./.github/actions/upload-artifact
        env:
          Package_Version: ${{ env.PACKAGE_VERSION }}