name: Build

on:
  push:
    branches:
      - master

jobs:
  Android:
    name: Android
    runs-on: ubuntu-latest
    steps:
      - name: Check out git repository
        uses: actions/checkout@v4

      - name: Setup Env
        uses: ./.github/actions/setup

      - name: Create debug keystore
        run: cd android && keytool -genkeypair -v -keystore debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US"

      - name: Build Packages
        env:
          DISABLE_SVG: 1
        run: |
          cd android
          ./gradlew assembleDebug

      - name: Get package version
        run: echo "PACKAGE_VERSION=$(node -p "\require('./package.json').version")" >> $GITHUB_ENV

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: lx-music-${{ env.PACKAGE_VERSION }}-debug
          path: android/app/build/outputs/apk/debug/*.apk
          retention-days: 30