name: Build

on:
  push:
    branches:
      - master

jobs:
  Android:
    name: Android
    runs-on: ubuntu-latest
    steps:
      - name: Check out git repository
        uses: actions/checkout@v4

      - name: Setup Env
        uses: ./.github/actions/setup

      - name: Create debug keystore
        run: |
          cd android
          # Create debug keystore for debug build
          keytool -genkeypair -v -keystore debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US"

      - name: Build Packages
        env:
          DISABLE_SVG: 1
        shell: bash
        run: |
          cd android
          # Build Debug APK
          ./gradlew assembleDebug

      - name: Get package version
        run: |
          Package_Version=$(node -p "require('./package.json').version")
          echo "PACKAGE_VERSION=$Package_Version" >> $GITHUB_ENV
          echo "APK_NAME=lx-music-mobile-v${Package_Version}-debug.apk" >> $GITHUB_ENV

      - name: Rename APK
        run: |
          cd android/app/build/outputs/apk/debug
          mv *.apk ${{ env.APK_NAME }}

      - name: Generate file MD5
        run: |
          cd android/app/build/outputs/apk/debug
          md5sum ${{ env.APK_NAME }}

      - name: Upload to Releases
        uses: softprops/action-gh-release@v1
        with:
          files: android/app/build/outputs/apk/debug/${{ env.APK_NAME }}
          generate_release_notes: true
          tag_name: ${{ env.PACKAGE_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}